# Profiles Config for Clash Verge

current: RSylbZsV69Jd
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1768609763
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1768609763
- uid: mSbivow0g7K3
  type: merge
  name: null
  file: mSbivow0g7K3.yaml
  updated: 1768609861
- uid: sVDw9jWjaXif
  type: script
  name: null
  file: sVDw9jWjaXif.js
  updated: 1768609861
- uid: roOyUC6l3tLV
  type: rules
  name: null
  file: roOyUC6l3tLV.yaml
  updated: 1768609861
- uid: pFKtlMMTCxjK
  type: proxies
  name: null
  file: pFKtlMMTCxjK.yaml
  updated: 1768609861
- uid: gJM94Az4JbJq
  type: groups
  name: null
  file: gJM94Az4JbJq.yaml
  updated: 1768609861
- uid: RwtvUmvfZOzw
  type: remote
  name: cfn-163
  file: RwtvUmvfZOzw.yaml
  desc: ''
  url: https://163cfn.232885.xyz/cfn/sub?target=clash
  selected:
  - name: 🐟 漏网之鱼
    now: ♻️ 自动选择
  - name: 🚀 手动选择
    now: ♻️ 自动选择
  updated: 1779074921
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: m5FlUYCHmOcV
    script: sTmWGNwlZBB0
    rules: rSSoCTvToOXh
    proxies: pItuzE1EwU0U
    groups: gGpEGYKXGKtE
- uid: RsObJcbon9Kg
  type: remote
  name: cfn-88
  file: RsObJcbon9Kg.yaml
  desc: ''
  url: https://cfn88.232885.qzz.io/cfn/sub?target=clash
  updated: 1779074923
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mrNdgHDYEBNF
    script: sl2VrhXxK9vj
    rules: rb7wTx0OciPd
    proxies: pmjuAKoxXXqk
    groups: gUN8PBck8f1r
- uid: RwWmv60H3j0A
  type: remote
  name: cfn-xqj
  file: RwWmv60H3j0A.yaml
  desc: ''
  url: https://xqjcfn.xuanqj.qzz.io/cfn/sub?target=clash
  selected:
  - name: 🐟 漏网之鱼
    now: ♻️ 自动选择
  updated: 1779074930
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    timeout_seconds: 60
    allow_auto_update: true
    merge: mSbivow0g7K3
    script: sVDw9jWjaXif
    rules: roOyUC6l3tLV
    proxies: pFKtlMMTCxjK
    groups: gJM94Az4JbJq
- uid: RT2I9eXxrIV0
  type: remote
  name: cml-163
  file: RT2I9eXxrIV0.yaml
  desc: ''
  url: https://163cml.232885.xyz/sub?token=c29f123519010e0895bf91e6b6abefba
  selected:
  - name: 🚀 节点选择
    now: ♻️ 自动选择
  updated: 1778644066
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mDB8CvPwNY8Q
    script: slAr2g0kOyN4
    rules: rR9cnyWKB2T9
    proxies: pAD9QFlY6A28
    groups: g5j0K6CWYqEI
  home: https://163cml.232885.xyz/admin
- uid: mdGxnSKEKjUn
  type: merge
  name: null
  file: mdGxnSKEKjUn.yaml
  updated: 1768609920
- uid: s4sNF3Pn0FC9
  type: script
  name: null
  file: s4sNF3Pn0FC9.js
  updated: 1768609920
- uid: rmRf7fFWR3bT
  type: rules
  name: null
  file: rmRf7fFWR3bT.yaml
  updated: 1768609920
- uid: pFkHTiZHcalR
  type: proxies
  name: null
  file: pFkHTiZHcalR.yaml
  updated: 1768609920
- uid: gJ9TeWSCxhZh
  type: groups
  name: null
  file: gJ9TeWSCxhZh.yaml
  updated: 1768609920
- uid: RSylbZsV69Jd
  type: remote
  name: cml-88
  file: RSylbZsV69Jd.yaml
  desc: ''
  url: https://cml88.232885.qzz.io/sub?token=ffe624e47c36175dd091122bd8336801
  selected:
  - name: ♻️ 自动选择
    now: 108.162.198.56
  - name: 🚀 节点选择
    now: 🔮 负载均衡
  - name: 🐟 漏网之鱼
    now: 🔯 故障转移
  extra:
    upload: 0
    download: 252
    total: 102400
    expire: 4102329600
  updated: 1779074928
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mdGxnSKEKjUn
    script: s4sNF3Pn0FC9
    rules: rmRf7fFWR3bT
    proxies: pFkHTiZHcalR
    groups: gJ9TeWSCxhZh
  home: https://cml88.232885.qzz.io/admin
- uid: m5FlUYCHmOcV
  type: merge
  name: null
  file: m5FlUYCHmOcV.yaml
  updated: 1773662019
- uid: sTmWGNwlZBB0
  type: script
  name: null
  file: sTmWGNwlZBB0.js
  updated: 1773662019
- uid: rSSoCTvToOXh
  type: rules
  name: null
  file: rSSoCTvToOXh.yaml
  updated: 1773662019
- uid: pItuzE1EwU0U
  type: proxies
  name: null
  file: pItuzE1EwU0U.yaml
  updated: 1773662019
- uid: gGpEGYKXGKtE
  type: groups
  name: null
  file: gGpEGYKXGKtE.yaml
  updated: 1773662019
- uid: m3cUum4y0W8g
  type: merge
  name: null
  file: m3cUum4y0W8g.yaml
  updated: 1773674809
- uid: s2asxW92rVfS
  type: script
  name: null
  file: s2asxW92rVfS.js
  updated: 1773674809
- uid: rzJas4BP5Tcr
  type: rules
  name: null
  file: rzJas4BP5Tcr.yaml
  updated: 1773674809
- uid: plJL5Ds6FSw5
  type: proxies
  name: null
  file: plJL5Ds6FSw5.yaml
  updated: 1773674809
- uid: g2J9gFVeWcA1
  type: groups
  name: null
  file: g2J9gFVeWcA1.yaml
  updated: 1773674809
- uid: RkC6ZKw3xEgi
  type: remote
  name: Quic
  file: RkC6ZKw3xEgi.yaml
  desc: ''
  url: https://www.gitlabip.xyz/Alvin9999/PAC/refs/heads/master/backup/img/1/2/ipp/quick/1/config.yaml
  updated: 1779074917
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: m3cUum4y0W8g
    script: s2asxW92rVfS
    rules: rzJas4BP5Tcr
    proxies: plJL5Ds6FSw5
    groups: g2J9gFVeWcA1
- uid: mDB8CvPwNY8Q
  type: merge
  name: null
  file: mDB8CvPwNY8Q.yaml
  updated: 1774324017
- uid: slAr2g0kOyN4
  type: script
  name: null
  file: slAr2g0kOyN4.js
  updated: 1774324017
- uid: rR9cnyWKB2T9
  type: rules
  name: null
  file: rR9cnyWKB2T9.yaml
  updated: 1774324017
- uid: pAD9QFlY6A28
  type: proxies
  name: null
  file: pAD9QFlY6A28.yaml
  updated: 1774324017
- uid: g5j0K6CWYqEI
  type: groups
  name: null
  file: g5j0K6CWYqEI.yaml
  updated: 1774324017
- uid: mrNdgHDYEBNF
  type: merge
  name: null
  file: mrNdgHDYEBNF.yaml
  updated: 1777390005
- uid: sl2VrhXxK9vj
  type: script
  name: null
  file: sl2VrhXxK9vj.js
  updated: 1777390005
- uid: rb7wTx0OciPd
  type: rules
  name: null
  file: rb7wTx0OciPd.yaml
  updated: 1777390005
- uid: pmjuAKoxXXqk
  type: proxies
  name: null
  file: pmjuAKoxXXqk.yaml
  updated: 1777390005
- uid: gUN8PBck8f1r
  type: groups
  name: null
  file: gUN8PBck8f1r.yaml
  updated: 1777390005
