# Profiles Config for Clash Verge

current: RaBFhQsycdEH
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1753157405
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1753157405
- uid: mdSsUrAK6z5A
  type: merge
  name: null
  file: mdSsUrAK6z5A.yaml
  updated: 1753325988
- uid: s4q0xUnl9M3m
  type: script
  name: null
  file: s4q0xUnl9M3m.js
  updated: 1753325988
- uid: r9Slro1qLQSJ
  type: rules
  name: null
  file: r9Slro1qLQSJ.yaml
  updated: 1753325988
- uid: pZ09ZpiaNjkY
  type: proxies
  name: null
  file: pZ09ZpiaNjkY.yaml
  updated: 1753325988
- uid: gftjOaFHRwML
  type: groups
  name: null
  file: gftjOaFHRwML.yaml
  updated: 1753325988
- uid: RFmE0U5jwt1F
  type: remote
  name: puddincat
  file: RFmE0U5jwt1F.yaml
  desc: ''
  url: https://gcore.jsdelivr.net/gh/PuddinCat/BestClash/proxies.yaml
  updated: 1763302846
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mdSsUrAK6z5A
    script: s4q0xUnl9M3m
    rules: r9Slro1qLQSJ
    proxies: pZ09ZpiaNjkY
    groups: gftjOaFHRwML
- uid: m5eY9rtJeCmo
  type: merge
  name: null
  file: m5eY9rtJeCmo.yaml
  updated: 1760661124
- uid: svZtKK93ClQQ
  type: script
  name: null
  file: svZtKK93ClQQ.js
  updated: 1760661124
- uid: rtjhJE7qoyLE
  type: rules
  name: null
  file: rtjhJE7qoyLE.yaml
  updated: 1760661124
- uid: pSAX0mylwLIv
  type: proxies
  name: null
  file: pSAX0mylwLIv.yaml
  updated: 1760661124
- uid: gFNuUqJYij1z
  type: groups
  name: null
  file: gFNuUqJYij1z.yaml
  updated: 1760661124
- uid: RSDeM9xvwbVZ
  type: remote
  name: xrqj
  file: RSDeM9xvwbVZ.yaml
  desc: cmliu项目
  url: https://xrqj.pages.dev/sub?token=2893513527d9c1c68e9e7f5d900712af
  extra:
    upload: 13048417439534
    download: 13048417439534
    total: 26388279066624
    expire: 4102329600
  updated: 1763077452
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: m5eY9rtJeCmo
    script: svZtKK93ClQQ
    rules: rtjhJE7qoyLE
    proxies: pSAX0mylwLIv
    groups: gFNuUqJYij1z
  home: https://xrqj.pages.dev/admin
- uid: mpWXfezvfCuU
  type: merge
  name: null
  file: mpWXfezvfCuU.yaml
  updated: 1760665894
- uid: sI3OnsECM7vh
  type: script
  name: null
  file: sI3OnsECM7vh.js
  updated: 1760665894
- uid: r1qxTKSmx7uS
  type: rules
  name: null
  file: r1qxTKSmx7uS.yaml
  updated: 1760665894
- uid: pVca1rF1U0BR
  type: proxies
  name: null
  file: pVca1rF1U0BR.yaml
  updated: 1760665894
- uid: gfagJ8HePaHV
  type: groups
  name: null
  file: gfagJ8HePaHV.yaml
  updated: 1760665894
- uid: RAaLVso74gIf
  type: remote
  name: dp88
  file: RAaLVso74gIf.yaml
  desc: cmliu项目
  url: https://dp88.dupontjoy.shop/sub?token=761ed334dfd4fac44feaf19583294287
  selected:
  - name: ♻️ 自动选择
    now: bestcf.030101.xyz
  extra:
    upload: 4780225299672
    download: 4780225299672
    total: 26388279066624
    expire: 4102329600
  updated: 1763023308
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mpWXfezvfCuU
    script: sI3OnsECM7vh
    rules: r1qxTKSmx7uS
    proxies: pVca1rF1U0BR
    groups: gfagJ8HePaHV
  home: https://dp88.dupontjoy.shop/admin
- uid: mMN9ow4hpgRh
  type: merge
  name: null
  file: mMN9ow4hpgRh.yaml
  updated: 1761371903
- uid: s6zE1BMSSR0U
  type: script
  name: null
  file: s6zE1BMSSR0U.js
  updated: 1761371903
- uid: rP6w3dgwXVNL
  type: rules
  name: null
  file: rP6w3dgwXVNL.yaml
  updated: 1761371903
- uid: prfhuKMRR2cx
  type: proxies
  name: null
  file: prfhuKMRR2cx.yaml
  updated: 1761371903
- uid: g2zSvyJjsJZr
  type: groups
  name: null
  file: g2zSvyJjsJZr.yaml
  updated: 1761371903
- uid: RzgKrJuL5u7s
  type: remote
  name: dp88bj
  file: RzgKrJuL5u7s.yaml
  desc: cfnew项目
  url: https://url.v1.mk/sub?target=clash&url=https%3A%2F%2Fdp88bj.dupontjoy.shop%2Fdp88bj%2Fsub&insert=false
  updated: 1763302846
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mMN9ow4hpgRh
    script: s6zE1BMSSR0U
    rules: rP6w3dgwXVNL
    proxies: prfhuKMRR2cx
    groups: g2zSvyJjsJZr
- uid: mNfajd829vzG
  type: merge
  name: null
  file: mNfajd829vzG.yaml
  updated: 1763180074
- uid: snrnBiYSRz1y
  type: script
  name: null
  file: snrnBiYSRz1y.js
  updated: 1763180074
- uid: rytyNP5QMTv4
  type: rules
  name: null
  file: rytyNP5QMTv4.yaml
  updated: 1763180074
- uid: pTehsOA0z09Q
  type: proxies
  name: null
  file: pTehsOA0z09Q.yaml
  updated: 1763180074
- uid: gn2snLXwudZ9
  type: groups
  name: null
  file: gn2snLXwudZ9.yaml
  updated: 1763180074
- uid: RaBFhQsycdEH
  type: remote
  name: 163cfn
  file: RaBFhQsycdEH.yaml
  desc: cfnew项目
  url: https://url.v1.mk/sub?target=clash&url=https%3A%2F%2F163cfn.232885.xyz%2F163cfn%2Fsub&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FbyJoey%2Ftest%2Frefs%2Fheads%2Fmain%2Ftist.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1763302842
  option:
    update_interval: 60
    allow_auto_update: true
    merge: mNfajd829vzG
    script: snrnBiYSRz1y
    rules: rytyNP5QMTv4
    proxies: pTehsOA0z09Q
    groups: gn2snLXwudZ9
