# Profiles Config for Clash Verge

current: RE2WWywsBQVi
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1753157405
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1753157405
- uid: mdSsUrAK6z5A
  type: merge
  name: null
  file: mdSsUrAK6z5A.yaml
  updated: 1753325988
- uid: s4q0xUnl9M3m
  type: script
  name: null
  file: s4q0xUnl9M3m.js
  updated: 1753325988
- uid: r9Slro1qLQSJ
  type: rules
  name: null
  file: r9Slro1qLQSJ.yaml
  updated: 1753325988
- uid: pZ09ZpiaNjkY
  type: proxies
  name: null
  file: pZ09ZpiaNjkY.yaml
  updated: 1753325988
- uid: gftjOaFHRwML
  type: groups
  name: null
  file: gftjOaFHRwML.yaml
  updated: 1753325988
- uid: RFmE0U5jwt1F
  type: remote
  name: puddincat
  file: RFmE0U5jwt1F.yaml
  desc: ''
  url: https://gcore.jsdelivr.net/gh/PuddinCat/BestClash/proxies.yaml
  updated: 1760089795
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: mdSsUrAK6z5A
    script: s4q0xUnl9M3m
    rules: r9Slro1qLQSJ
    proxies: pZ09ZpiaNjkY
    groups: gftjOaFHRwML
- uid: m6qq8sSjcBuS
  type: merge
  name: null
  file: m6qq8sSjcBuS.yaml
  updated: 1753337152
- uid: sktu5UCedddL
  type: script
  name: null
  file: sktu5UCedddL.js
  updated: 1753337152
- uid: r8a1djmYI7s8
  type: rules
  name: null
  file: r8a1djmYI7s8.yaml
  updated: 1753337152
- uid: p7pHEmGQahyE
  type: proxies
  name: null
  file: p7pHEmGQahyE.yaml
  updated: 1753337152
- uid: gEKSUYnnUw76
  type: groups
  name: null
  file: gEKSUYnnUw76.yaml
  updated: 1753337152
- uid: RE2WWywsBQVi
  type: remote
  name: yzxr
  file: RE2WWywsBQVi.yaml
  desc: ''
  url: https://yzxr.dupontjoy.shop/yzxr?proxyip=proxyip.cmliussss.net:443
  extra:
    upload: 5405712572993
    download: 5405712572993
    total: 26388279066624
    expire: 4102329600
  updated: 1760089797
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: m6qq8sSjcBuS
    script: sktu5UCedddL
    rules: r8a1djmYI7s8
    proxies: p7pHEmGQahyE
    groups: gEKSUYnnUw76
  home: https://yzxr.dupontjoy.shop/yzxr
