# Profiles Config for Clash Verge

current: R1mXxj5uJFzg
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1768609763
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1768609763
- uid: mQ65tQOB0HLw
  type: merge
  name: null
  file: mQ65tQOB0HLw.yaml
  updated: 1768609826
- uid: sHrEZEATmNHd
  type: script
  name: null
  file: sHrEZEATmNHd.js
  updated: 1768609826
- uid: rvoGjw9lDo1O
  type: rules
  name: null
  file: rvoGjw9lDo1O.yaml
  updated: 1768609826
- uid: pyqCKl0B2Byk
  type: proxies
  name: null
  file: pyqCKl0B2Byk.yaml
  updated: 1768609826
- uid: gbKzlXk9CziP
  type: groups
  name: null
  file: gbKzlXk9CziP.yaml
  updated: 1768609826
- uid: RzKJ34RrWjNV
  type: remote
  name: 163cfn
  file: RzKJ34RrWjNV.yaml
  desc: ''
  url: https://api.asailor.org/sub?target=clash&url=https://163cfn.232885.xyz/163cfn/sub&insert=false&config=https://raw.githubusercontent.com/byJoey/test/refs/heads/main/tist.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1768613454
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mQ65tQOB0HLw
    script: sHrEZEATmNHd
    rules: rvoGjw9lDo1O
    proxies: pyqCKl0B2Byk
    groups: gbKzlXk9CziP
- uid: mSbivow0g7K3
  type: merge
  name: null
  file: mSbivow0g7K3.yaml
  updated: 1768609861
- uid: sVDw9jWjaXif
  type: script
  name: null
  file: sVDw9jWjaXif.js
  updated: 1768609861
- uid: roOyUC6l3tLV
  type: rules
  name: null
  file: roOyUC6l3tLV.yaml
  updated: 1768609861
- uid: pFKtlMMTCxjK
  type: proxies
  name: null
  file: pFKtlMMTCxjK.yaml
  updated: 1768609861
- uid: gJM94Az4JbJq
  type: groups
  name: null
  file: gJM94Az4JbJq.yaml
  updated: 1768609861
- uid: RwWmv60H3j0A
  type: remote
  name: dp88bj
  file: RwWmv60H3j0A.yaml
  desc: ''
  url: https://api.asailor.org/sub?target=clash&url=https://dp88bj.dupontjoy.shop/dp88bj/sub&insert=false&config=https://raw.githubusercontent.com/byJoey/test/refs/heads/main/tist.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1768613475
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mSbivow0g7K3
    script: sVDw9jWjaXif
    rules: roOyUC6l3tLV
    proxies: pFKtlMMTCxjK
    groups: gJM94Az4JbJq
- uid: mdGxnSKEKjUn
  type: merge
  name: null
  file: mdGxnSKEKjUn.yaml
  updated: 1768609920
- uid: s4sNF3Pn0FC9
  type: script
  name: null
  file: s4sNF3Pn0FC9.js
  updated: 1768609920
- uid: rmRf7fFWR3bT
  type: rules
  name: null
  file: rmRf7fFWR3bT.yaml
  updated: 1768609920
- uid: pFkHTiZHcalR
  type: proxies
  name: null
  file: pFkHTiZHcalR.yaml
  updated: 1768609920
- uid: gJ9TeWSCxhZh
  type: groups
  name: null
  file: gJ9TeWSCxhZh.yaml
  updated: 1768609920
- uid: RSylbZsV69Jd
  type: remote
  name: dp88
  file: RSylbZsV69Jd.yaml
  desc: ''
  url: https://dp88.dupontjoy.shop/sub?token=67f57a485b7ec464ba3eb735f54b82f9
  extra:
    upload: 872960005651
    download: 872960005651
    total: 26388279066624
    expire: 4102329600
  updated: 1768613720
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mdGxnSKEKjUn
    script: s4sNF3Pn0FC9
    rules: rmRf7fFWR3bT
    proxies: pFkHTiZHcalR
    groups: gJ9TeWSCxhZh
  home: https://dp88.dupontjoy.shop/admin
- uid: mCwMAmsa9Tfw
  type: merge
  name: null
  file: mCwMAmsa9Tfw.yaml
  updated: 1768609969
- uid: sBQkhM9LIXzn
  type: script
  name: null
  file: sBQkhM9LIXzn.js
  updated: 1768609969
- uid: rVBQZaAI7dna
  type: rules
  name: null
  file: rVBQZaAI7dna.yaml
  updated: 1768609969
- uid: pITwuSvbv03f
  type: proxies
  name: null
  file: pITwuSvbv03f.yaml
  updated: 1768609969
- uid: ghZ9kUzXAIiM
  type: groups
  name: null
  file: ghZ9kUzXAIiM.yaml
  updated: 1768609969
- uid: R1mXxj5uJFzg
  type: remote
  name: xrqj
  file: R1mXxj5uJFzg.yaml
  desc: ''
  url: https://xrqj.232885.xyz/sub?token=6a4ea620288c3476b8c4dfc7b97378f6
  extra:
    upload: 872962296301
    download: 872962296301
    total: 26388279066624
    expire: 4102329600
  updated: 1768613720
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mCwMAmsa9Tfw
    script: sBQkhM9LIXzn
    rules: rVBQZaAI7dna
    proxies: pITwuSvbv03f
    groups: ghZ9kUzXAIiM
  home: https://xrqj.232885.xyz/admin
