# Profiles Config for Clash Verge

current: RE2WWywsBQVi
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1753157405
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1753157405
- uid: mdSsUrAK6z5A
  type: merge
  name: null
  file: mdSsUrAK6z5A.yaml
  updated: 1753325988
- uid: s4q0xUnl9M3m
  type: script
  name: null
  file: s4q0xUnl9M3m.js
  updated: 1753325988
- uid: r9Slro1qLQSJ
  type: rules
  name: null
  file: r9Slro1qLQSJ.yaml
  updated: 1753325988
- uid: pZ09ZpiaNjkY
  type: proxies
  name: null
  file: pZ09ZpiaNjkY.yaml
  updated: 1753325988
- uid: gftjOaFHRwML
  type: groups
  name: null
  file: gftjOaFHRwML.yaml
  updated: 1753325988
- uid: RFmE0U5jwt1F
  type: remote
  name: puddincat
  file: RFmE0U5jwt1F.yaml
  desc: ''
  url: https://gcore.jsdelivr.net/gh/PuddinCat/BestClash/proxies.yaml
  updated: 1760791682
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: mdSsUrAK6z5A
    script: s4q0xUnl9M3m
    rules: r9Slro1qLQSJ
    proxies: pZ09ZpiaNjkY
    groups: gftjOaFHRwML
- uid: m6qq8sSjcBuS
  type: merge
  name: null
  file: m6qq8sSjcBuS.yaml
  updated: 1753337152
- uid: sktu5UCedddL
  type: script
  name: null
  file: sktu5UCedddL.js
  updated: 1753337152
- uid: r8a1djmYI7s8
  type: rules
  name: null
  file: r8a1djmYI7s8.yaml
  updated: 1753337152
- uid: p7pHEmGQahyE
  type: proxies
  name: null
  file: p7pHEmGQahyE.yaml
  updated: 1753337152
- uid: gEKSUYnnUw76
  type: groups
  name: null
  file: gEKSUYnnUw76.yaml
  updated: 1753337152
- uid: RE2WWywsBQVi
  type: remote
  name: yzxr
  file: RE2WWywsBQVi.yaml
  desc: ''
  url: https://yzxr.pages.dev/yzxr?proxyip=proxyip.cmliussss.net:443
  extra:
    upload: 7037249473399
    download: 7037249473399
    total: 26388279066624
    expire: 4102329600
  updated: 1760791682
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: m6qq8sSjcBuS
    script: sktu5UCedddL
    rules: r8a1djmYI7s8
    proxies: p7pHEmGQahyE
    groups: gEKSUYnnUw76
  home: https://yzxr.pages.dev/yzxr
- uid: m5eY9rtJeCmo
  type: merge
  name: null
  file: m5eY9rtJeCmo.yaml
  updated: 1760661124
- uid: svZtKK93ClQQ
  type: script
  name: null
  file: svZtKK93ClQQ.js
  updated: 1760661124
- uid: rtjhJE7qoyLE
  type: rules
  name: null
  file: rtjhJE7qoyLE.yaml
  updated: 1760661124
- uid: pSAX0mylwLIv
  type: proxies
  name: null
  file: pSAX0mylwLIv.yaml
  updated: 1760661124
- uid: gFNuUqJYij1z
  type: groups
  name: null
  file: gFNuUqJYij1z.yaml
  updated: 1760661124
- uid: RSDeM9xvwbVZ
  type: remote
  name: xrqj
  file: RSDeM9xvwbVZ.yaml
  desc: ''
  url: https://xrqj.pages.dev/xrqj?proxyip=proxyip.cmliussss.net:443
  extra:
    upload: 7037238630993
    download: 7037238630993
    total: 26388279066624
    expire: 4102329600
  updated: 1760791683
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: m5eY9rtJeCmo
    script: svZtKK93ClQQ
    rules: rtjhJE7qoyLE
    proxies: pSAX0mylwLIv
    groups: gFNuUqJYij1z
  home: https://xrqj.pages.dev/xrqj
- uid: mpWXfezvfCuU
  type: merge
  name: null
  file: mpWXfezvfCuU.yaml
  updated: 1760665894
- uid: sI3OnsECM7vh
  type: script
  name: null
  file: sI3OnsECM7vh.js
  updated: 1760665894
- uid: r1qxTKSmx7uS
  type: rules
  name: null
  file: r1qxTKSmx7uS.yaml
  updated: 1760665894
- uid: pVca1rF1U0BR
  type: proxies
  name: null
  file: pVca1rF1U0BR.yaml
  updated: 1760665894
- uid: gfagJ8HePaHV
  type: groups
  name: null
  file: gfagJ8HePaHV.yaml
  updated: 1760665894
- uid: RAaLVso74gIf
  type: remote
  name: dp88
  file: RAaLVso74gIf.yaml
  desc: ''
  url: https://dp88.dupontjoy.shop/dp88?proxyip=proxyip.cmliussss.net:443
  extra:
    upload: 7037213281141
    download: 7037213281141
    total: 26388279066624
    expire: 4102329600
  updated: 1760791682
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 120
    merge: mpWXfezvfCuU
    script: sI3OnsECM7vh
    rules: r1qxTKSmx7uS
    proxies: pVca1rF1U0BR
    groups: gfagJ8HePaHV
  home: https://dp88.dupontjoy.shop/dp88
