# Profiles Config for Clash Verge

current: RUkEKBpwWGFO
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1753157405
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1753157405
- uid: mdSsUrAK6z5A
  type: merge
  name: null
  file: mdSsUrAK6z5A.yaml
  updated: 1753325988
- uid: s4q0xUnl9M3m
  type: script
  name: null
  file: s4q0xUnl9M3m.js
  updated: 1753325988
- uid: r9Slro1qLQSJ
  type: rules
  name: null
  file: r9Slro1qLQSJ.yaml
  updated: 1753325988
- uid: pZ09ZpiaNjkY
  type: proxies
  name: null
  file: pZ09ZpiaNjkY.yaml
  updated: 1753325988
- uid: gftjOaFHRwML
  type: groups
  name: null
  file: gftjOaFHRwML.yaml
  updated: 1753325988
- uid: RFmE0U5jwt1F
  type: remote
  name: puddincat
  file: RFmE0U5jwt1F.yaml
  desc: ''
  url: https://gcore.jsdelivr.net/gh/PuddinCat/BestClash/proxies.yaml
  updated: 1766833496
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 30
    allow_auto_update: true
    merge: mdSsUrAK6z5A
    script: s4q0xUnl9M3m
    rules: r9Slro1qLQSJ
    proxies: pZ09ZpiaNjkY
    groups: gftjOaFHRwML
- uid: mMcRTtDq8U0c
  type: merge
  name: null
  file: mMcRTtDq8U0c.yaml
  updated: 1764940467
- uid: sVNOAFXhrBYA
  type: script
  name: null
  file: sVNOAFXhrBYA.js
  updated: 1764940467
- uid: raUXqTRF2OEd
  type: rules
  name: null
  file: raUXqTRF2OEd.yaml
  updated: 1764940467
- uid: p2xad9Vbnu5P
  type: proxies
  name: null
  file: p2xad9Vbnu5P.yaml
  updated: 1764940467
- uid: gUESsIyp5gwF
  type: groups
  name: null
  file: gUESsIyp5gwF.yaml
  updated: 1764940467
- uid: RPCQGeAoLnyE
  type: remote
  name: xrqj
  file: RPCQGeAoLnyE.yaml
  desc: xrqj邮箱-cmliu项目
  url: https://xrqj.pages.dev/sub?token=7861ff9c5fb7ab85e740b07639cc3f9b
  selected:
  - name: 🚀 节点选择
    now: ♻️ 自动选择
  extra:
    upload: 5877959230940
    download: 5877959230940
    total: 26388279066624
    expire: 4102329600
  updated: 1766832092
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mMcRTtDq8U0c
    script: sVNOAFXhrBYA
    rules: raUXqTRF2OEd
    proxies: p2xad9Vbnu5P
    groups: gUESsIyp5gwF
  home: https://xrqj.pages.dev/admin
- uid: m2pPN2puQ2A5
  type: merge
  name: null
  file: m2pPN2puQ2A5.yaml
  updated: 1764940505
- uid: srHOGryHMtbP
  type: script
  name: null
  file: srHOGryHMtbP.js
  updated: 1764940505
- uid: rXoUuZOhQmuh
  type: rules
  name: null
  file: rXoUuZOhQmuh.yaml
  updated: 1764940505
- uid: pS1cl7usYdDb
  type: proxies
  name: null
  file: pS1cl7usYdDb.yaml
  updated: 1764940505
- uid: gCClPran3bXH
  type: groups
  name: null
  file: gCClPran3bXH.yaml
  updated: 1764940505
- uid: R6dfsAL7TSgZ
  type: remote
  name: dp88
  file: R6dfsAL7TSgZ.yaml
  desc: 88邮箱-cmliu项目
  url: https://dp88.dupontjoy.shop/sub?token=67f57a485b7ec464ba3eb735f54b82f9
  selected:
  - name: ♻️ 自动选择
    now: mfa.gov.ua
  - name: 🚀 节点选择
    now: bestcf.030101.xyz
  extra:
    upload: 5877928841660
    download: 5877928841660
    total: 26388279066624
    expire: 4102329600
  updated: 1766832093
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: m2pPN2puQ2A5
    script: srHOGryHMtbP
    rules: rXoUuZOhQmuh
    proxies: pS1cl7usYdDb
    groups: gCClPran3bXH
  home: https://dp88.dupontjoy.shop/admin
- uid: m4CfthHvnE5H
  type: merge
  name: null
  file: m4CfthHvnE5H.yaml
  updated: 1764940559
- uid: sdJhSCTjhv0p
  type: script
  name: null
  file: sdJhSCTjhv0p.js
  updated: 1764940559
- uid: rU2012b1E1AE
  type: rules
  name: null
  file: rU2012b1E1AE.yaml
  updated: 1764940559
- uid: pLXwSLHgFQ0N
  type: proxies
  name: null
  file: pLXwSLHgFQ0N.yaml
  updated: 1764940559
- uid: gj8YvGcm6HNk
  type: groups
  name: null
  file: gj8YvGcm6HNk.yaml
  updated: 1764940559
- uid: RUkEKBpwWGFO
  type: remote
  name: dp88bj
  file: RUkEKBpwWGFO.yaml
  desc: 88邮箱-cfnew项目
  url: https://api.asailor.org/sub?target=clash&url=https://dp88bj.dupontjoy.shop/dp88bj/sub&insert=false&config=https://raw.githubusercontent.com/byJoey/test/refs/heads/main/tist.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1766832092
  option:
    update_interval: 60
    allow_auto_update: true
    merge: m4CfthHvnE5H
    script: sdJhSCTjhv0p
    rules: rU2012b1E1AE
    proxies: pLXwSLHgFQ0N
    groups: gj8YvGcm6HNk
- uid: mUDlInZqFjkk
  type: merge
  name: null
  file: mUDlInZqFjkk.yaml
  updated: 1764940596
- uid: sgjhzbgsKIrT
  type: script
  name: null
  file: sgjhzbgsKIrT.js
  updated: 1764940596
- uid: rzXP2YGFUA59
  type: rules
  name: null
  file: rzXP2YGFUA59.yaml
  updated: 1764940596
- uid: pT2exACH8gIk
  type: proxies
  name: null
  file: pT2exACH8gIk.yaml
  updated: 1764940596
- uid: gvk56mBopFu0
  type: groups
  name: null
  file: gvk56mBopFu0.yaml
  updated: 1764940596
- uid: RZMwOHf9XhCv
  type: remote
  name: 163cfn
  file: RZMwOHf9XhCv.yaml
  desc: 163邮箱-cfnew项目
  url: https://api.asailor.org/sub?target=clash&url=https://163cfn.232885.xyz/163cfn/sub&insert=false&config=https://raw.githubusercontent.com/byJoey/test/refs/heads/main/tist.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1766832093
  option:
    update_interval: 60
    allow_auto_update: true
    merge: mUDlInZqFjkk
    script: sgjhzbgsKIrT
    rules: rzXP2YGFUA59
    proxies: pT2exACH8gIk
    groups: gvk56mBopFu0
- uid: mMmSW77x6R97
  type: merge
  name: null
  file: mMmSW77x6R97.yaml
  updated: 1764940655
- uid: s2QAgsJOZoqW
  type: script
  name: null
  file: s2QAgsJOZoqW.js
  updated: 1764940655
- uid: r6RcsyLYlxSL
  type: rules
  name: null
  file: r6RcsyLYlxSL.yaml
  updated: 1764940655
- uid: pPZQS5PDBjKn
  type: proxies
  name: null
  file: pPZQS5PDBjKn.yaml
  updated: 1764940655
- uid: glSQjtdq78I1
  type: groups
  name: null
  file: glSQjtdq78I1.yaml
  updated: 1764940655
- uid: RmNCzEs2xYTb
  type: remote
  name: dp88bj-ops转换
  file: RmNCzEs2xYTb.yaml
  desc: 88邮箱-cfnew项目-ops转换
  url: https://s.ops.ci/YdShjdL
  selected:
  - name: ♻️ 自动选择
    now: cf.090227.xyz-443-Trojan-WS-TLS
  updated: 1766832097
  option:
    update_interval: 59
    allow_auto_update: true
    merge: mMmSW77x6R97
    script: s2QAgsJOZoqW
    rules: r6RcsyLYlxSL
    proxies: pPZQS5PDBjKn
    groups: glSQjtdq78I1
- uid: miryPXyNW8OX
  type: merge
  name: null
  file: miryPXyNW8OX.yaml
  updated: 1764940707
- uid: sdLEPvnQQBJq
  type: script
  name: null
  file: sdLEPvnQQBJq.js
  updated: 1764940707
- uid: rH62DXUODQJP
  type: rules
  name: null
  file: rH62DXUODQJP.yaml
  updated: 1764940707
- uid: pmGFPSnuDdqq
  type: proxies
  name: null
  file: pmGFPSnuDdqq.yaml
  updated: 1764940707
- uid: g07yeHTmdvDN
  type: groups
  name: null
  file: g07yeHTmdvDN.yaml
  updated: 1764940707
- uid: Ry0fXYTU2GbC
  type: remote
  name: 163cfn-ops转换
  file: Ry0fXYTU2GbC.yaml
  desc: 163邮箱-cfnew项目-ops转换
  url: https://s.ops.ci/bFJFfEd
  updated: 1766832097
  option:
    update_interval: 60
    allow_auto_update: true
    merge: miryPXyNW8OX
    script: sdLEPvnQQBJq
    rules: rH62DXUODQJP
    proxies: pmGFPSnuDdqq
    groups: g07yeHTmdvDN
