; Generated (14.07.2026 19:06:19) by Firewall App Blocker v1.9
; www.sordum.org

[FirewallRules]
0=C:\Users\Cing\AppData\Local\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe|Microsoft Edge Update
0=C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe|Microsoft Edge Update
0=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost64.exe|ListaryHookHost64
0=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost32.exe|ListaryHookHost32
0=D:\Program Files\CingFox\Software\Listary6\listary-core.exe|listary-core
0=D:\Program Files\CingFox\Software\Listary6\Listary.Service.exe|Listary.Service
0=D:\Program Files\CingFox\Software\Listary6\Listary.FileAppPlugin.DevTools.exe|Listary.FileAppPlugin.DevTools
0=D:\Program Files\CingFox\Software\Listary6\Listary.exe|Listary
0=D:\Program Files\CingFox\Software\Listary6\Listary.Diagnostics.exe|Listary.Diagnostics
6=D:\Program Files\lx-music-desktop\lx-music-desktop.exe|lx-music-desktop
4=C:\Users\Cing\AppData\Local\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe|Microsoft Edge Update
4=C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe|Microsoft Edge Update
4=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost64.exe|ListaryHookHost64
4=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost32.exe|ListaryHookHost32
4=D:\Program Files\CingFox\Software\Listary6\listary-core.exe|listary-core
4=D:\Program Files\CingFox\Software\Listary6\Listary.Service.exe|Listary.Service
4=D:\Program Files\CingFox\Software\Listary6\Listary.FileAppPlugin.DevTools.exe|Listary.FileAppPlugin.DevTools
4=D:\Program Files\CingFox\Software\Listary6\Listary.exe|Listary
4=D:\Program Files\CingFox\Software\Listary6\Listary.Diagnostics.exe|Listary.Diagnostics
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\wpspdf.exe|wpspdf.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\et.exe|et.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\wpp.exe|wpp.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\wpslingxi.exe|wpslingxi.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\promecefpluginhost.exe|promecefpluginhost.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\wpscloudsvr.exe|wpscloudsvr.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26884\office6\wps.exe|wps.exe
6=C:\Program Files\Nutstore\bin-7.2.12\NutstoreClient.exe|NutstoreDesktopClient
6=C:\Program Files\Nutstore\bin-7.2.9\NutstoreClient.exe|NutstoreDesktopClient
