; Generated (04.06.2026 20:40:38) by Firewall App Blocker v1.9
; www.sordum.org

[FirewallRules]
0=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost64.exe|ListaryHookHost64
0=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost32.exe|ListaryHookHost32
0=D:\Program Files\CingFox\Software\Listary6\listary-core.exe|listary-core
0=D:\Program Files\CingFox\Software\Listary6\Listary.Service.exe|Listary.Service
0=D:\Program Files\CingFox\Software\Listary6\Listary.exe|Listary
0=C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe|Microsoft Edge Update
4=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost64.exe|ListaryHookHost64
4=D:\Program Files\CingFox\Software\Listary6\ListaryHookHost32.exe|ListaryHookHost32
4=D:\Program Files\CingFox\Software\Listary6\listary-core.exe|listary-core
4=D:\Program Files\CingFox\Software\Listary6\Listary.Service.exe|Listary.Service
4=D:\Program Files\CingFox\Software\Listary6\Listary.exe|Listary
4=C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe|Microsoft Edge Update
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26373\office6\wps.exe|wps.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26373\office6\wpslingxi.exe|wpslingxi.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26373\office6\promecefpluginhost.exe|promecefpluginhost.exe
6=C:\Program Files\Kingsoft\WPS Office\12.1.0.26373\office6\wpscloudsvr.exe|wpscloudsvr.exe
6=D:\Program Files\MuMuPlayer\nx_device\12.0\shell\aria2.exe|NXDeviceAria2
6=D:\Program Files\MuMuPlayer\nx_device\12.0\shell\MuMuNxDevice.exe|MuMuNxDevice
6=D:\Program Files\MuMuPlayer\nx_main\MuMuNxMain.exe|MuMuNxMain
6=D:\Program Files\MuMuPlayer\nx_main\aria2.exe|NXMainAria2
6=C:\Program Files\Nutstore\bin-7.2.11\NutstoreClient.exe|NutstoreDesktopClient
6=C:\Program Files\MuMuVMMVbox\Hypervisor\MuMuVMMHeadless.exe|MuMuVMMHeadless
6=C:\Program Files\MuMuVMMVbox\Hypervisor\MuMuVMMSVC.exe|MuMuVMMSVC
